config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :transactions

  get "transactions/:id/complete", to: "transactions#complete", as: 'complete_transaction'

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/transaction.rb
class Transaction < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  def index
    @transactions = Transaction.all
  end

  def show
    @transaction = Transaction.find(params[:id])
  end

  def new
    @transaction = Transaction.new
  end

  def edit
    @transaction = Transaction.find(params[:id])
  end

  def complete
    @transaction = Transaction.find(params[:id])
  end

  def create
    @transaction = Transaction.new(transaction_params)

    if @transaction.save
      redirect_to @transaction
    else
      render 'new'
    end
  end

  def update
    @transaction = Transaction.find(params[:id])

    if @transaction.update(transaction_params)
      redirect_to @transaction
    else
      render 'edit'
    end
  end

  def destroy
    @transaction = Transaction.find(params[:id])
    @transaction.destroy

    redirect_to transactions_path
  end

  private
    def transaction_params
      params.require(:transaction).permit(:name, :payment_method, :amount, :submit_date, :status)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @upcoming_manual_transactions = Transaction.where("status = ? AND submit_date < ?", "manual", Date.today+31)
    @upcoming_automatic_transactions = Transaction.where("status = ? AND submit_date < ?", "automatic", Date.today+31)
    @pending_transactions = Transaction.where(status: "pending")

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinanceManagerRuby</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/transactions/_form.html.erb
<%= form_with model: @transaction, local: true do |form| %>

  <% if @transaction.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@transaction.errors.count, "error") %> prohibited
        this transaction from being saved:
      </h2>
      <ul>
        <% @transaction.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.label :payment_method %><br>
    <%= form.text_field :payment_method %>
  </p>

  <p>
    <%= form.label :amount %><br>
    <%= form.text_field :amount %>
  </p>

  <p>
    <%= form.label :submit_date %><br>
    <%= form.date_field :submit_date %>
  </p>

  <p>
    <%= form.label :status %><br>
    <%= form.select :status, ["completed","pending","automatic","manual"] %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>

app/views/transactions/edit.html.erb
<h1>Edit transaction</h1>

<%= render 'form' %>

<%= link_to 'Back', transactions_path %>

app/views/transactions/index.html.erb
<h1>Transactions</h1>

<%= link_to 'Back', root_path %> | <%= link_to 'New transaction', new_transaction_path %>

<table>
  <tr>
    <th>Name</th>
    <th>Payment Method</th>
    <th>Amount</th>
    <th>Submit Date</th>
    <th>Status</th>
    <th colspan="3"></th>
  </tr>

  <% @transactions.each do |transaction| %>
    <tr>
      <td><%= transaction.name %></td>
      <td><%= transaction.payment_method %></td>
      <td align="right"><%= number_to_currency(transaction.amount) %></td>
      <td><%= transaction.submit_date.strftime("%b %d %Y") %></td>
      <td><%= transaction.status %></td>
      <td><%= link_to 'Show', transaction_path(transaction) %></td>
      <td><%= link_to 'Edit', edit_transaction_path(transaction) %></td>
      <td><%= link_to 'Delete', transaction_path(transaction), method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/transactions/new.html.erb
<h1>New Transaction</h1>

<%= render 'form' %>

<%= link_to 'Back', transactions_path %>

app/views/transactions/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @transaction.name %>
</p>

<p>
  <strong>Payment Method:</strong>
  <%= @transaction.payment_method %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @transaction.amount %>
</p>

<p>
  <strong>Submit Date:</strong>
  <%= @transaction.submit_date.strftime("%b %d %Y") %>
</p>

<p>
  <strong>Status:</strong>
  <%= @transaction.status %>
</p>

<%= link_to 'Edit', edit_transaction_path(@transaction) %> |
<%= link_to 'Back', transactions_path %>

app/views/welcome/index.html.erb
<h1>Finance Manager</h1>
<%= link_to 'Transactions', controller: 'transactions' %>

<h2>Upcoming manual transactions</h2>
<table>
  <tr>
    <th>Date</th>
    <th>Name</th>
    <th>Amount</th>
    <th>Payment Method</th>
    <th></th>
  </tr>
  <% @upcoming_manual_transactions.each do |transaction| %>
    <tr>
      <td><%= transaction.submit_date.strftime("%b %d") %></td>
      <td><%= transaction.name %></td>
      <td align="right"><%= number_to_currency(transaction.amount) %></td>
      <td><%= transaction.payment_method %></td>
      <td><%= link_to 'Edit', edit_transaction_path(transaction) %></td>
    </tr>
  <% end %>
</table>

<h2>Upcoming automatic transactions</h2>
<table>
  <tr>
    <th>Date</th>
    <th>Name</th>
    <th>Amount</th>
    <th>Payment Method</th>
    <th></th>
  </tr>
  <% @upcoming_automatic_transactions.each do |transaction| %>
    <tr>
      <td><%= transaction.submit_date.strftime("%b %d") %></td>
      <td><%= transaction.name %></td>
      <td align="right"><%= number_to_currency(transaction.amount) %></td>
      <td><%= transaction.payment_method %></td>
      <td><%= link_to 'Edit', edit_transaction_path(transaction) %></td>
    </tr>
  <% end %>
</table>

<h2>Pending transactions</h2>
<table>
  <tr>
    <th>Date</th>
    <th>Name</th>
    <th>Amount</th>
    <th>Payment Method</th>
    <th></th>
  </tr>
  <% @pending_transactions.each do |transaction| %>
    <tr>
      <td><%= transaction.submit_date.strftime("%b %d") %></td>
      <td><%= transaction.name %></td>
      <td align="right"><%= number_to_currency(transaction.amount) %></td>
      <td><%= transaction.payment_method %></td>
      <td><%= link_to 'Complete', complete_transaction_path(transaction) %></td>
      <!--td><%= link_to 'Delete', transaction_path(transaction), method: :delete, data: { confirm: 'Are you sure?' } %></td-->
    </tr>
  <% end %>
</table>